export const boardMeta = {
  title: 'KRISEVA ATTEST · evidence review wireframes',
  subtitle: 'Seven low-fidelity screens for a bounded, human-reviewed evidence integrity workbench.',
  caseName: 'Meridian Horizon Fund I',
  fme: 'Meridian Horizon Fund Management IFSC Pvt Ltd',
  period: 'Quarter ended 30 June 2026',
  marker: 'SYNTHETIC DEMO DATA',
  boundary: 'RESEARCH-STAGE INTERFACE · NOT A REGULATORY FILING · HUMAN DECISION REQUIRED',
};

export const screens = [
  {
    number: '01',
    slug: 'case-dashboard',
    name: 'Case dashboard',
    task: 'Orient a reviewer to one synthetic case, its source inventory, and the three-field evidence state.',
    action: 'Open source-to-field workspace',
    error: 'Before review: keep all three fields PENDING. Never infer progress from source count.',
    mobile: 'Collapse inventory below the field index; keep the human-decision boundary above the fold.',
    panels: [
      { label: 'Case register', title: 'QE 30 Jun 2026 · pre-submission evidence review', body: '3 synthetic sources · 3 governed fields', meta: 'CASE / meridian-horizon-q2-2026' },
      { label: 'Field index', title: '01 Closing NAV', body: 'SUPPORTED · two normalized values agree', meta: 'USD 12,400,000' },
      { label: 'Field index', title: '02 Committed capital', body: 'CONFLICTING · no default winner', meta: 'USD 25,000,000 ≠ USD 24,000,000' },
      { label: 'Field index', title: '03 Investor complaints closed', body: 'UNSUPPORTED · evidence request required', meta: 'NO CANDIDATE SOURCE' },
    ],
  },
  {
    number: '02',
    slug: 'source-workspace',
    name: 'Source-to-field workspace',
    task: 'Compare a proposed field value with exact page, row, sheet, and cell coordinates before a human acts.',
    action: 'Send disagreement to conflict queue',
    error: 'If a source preview cannot load, retain its fingerprint and mark the candidate unavailable; do not guess.',
    mobile: 'Show one source at a time; stack coordinates directly above the review action.',
    panels: [
      { label: 'Selected field', title: 'Committed capital', body: 'Agent path: deterministic evidence comparison', meta: 'STATUS / CONFLICTING' },
      { label: 'Candidate A', title: 'USD 25,000,000', body: 'Administrator statement', meta: 'PAGE 2 · ROW COMMITTED CAPITAL' },
      { label: 'Candidate B', title: 'USD 24,000,000', body: 'Subscription register extract', meta: 'SCHEDULE A · CELL C11' },
      { label: 'Source custody', title: 'Fingerprints retained', body: 'synthetic:admin-statement:9b2d7f', meta: 'synthetic:board-schedule:4f71aa' },
    ],
  },
  {
    number: '03',
    slug: 'conflict-queue',
    name: 'Conflict queue',
    task: 'Make a disagreement impossible to miss and require a named human to select, correct, reject, or defer.',
    action: 'Record human decision',
    error: 'Block the action until reviewer, source selection, and decision reason are present.',
    mobile: 'Stack candidates without reordering; repeat each coordinate beside its value.',
    panels: [
      { label: 'Conflict 01 / 01', title: 'Two sources disagree', body: 'Committed capital has two unequal normalized values.', meta: 'NO DEFAULT WINNER' },
      { label: 'Candidate A', title: 'USD 25,000,000', body: 'Administrator statement', meta: 'PAGE 2 · ROW COMMITTED CAPITAL' },
      { label: 'Candidate B', title: 'USD 24,000,000', body: 'Subscription register extract', meta: 'SCHEDULE A · CELL C11' },
      { label: 'Decision record', title: 'Reviewer name required', body: 'Reason required · selection required', meta: 'ACCEPT / CORRECT / REJECT / DEFER' },
    ],
  },
  {
    number: '04',
    slug: 'agent-trace',
    name: 'Agent trace',
    task: 'Expose the bounded comparison path, inputs used, candidate output, and explicit abstention.',
    action: 'Return to unresolved fields',
    error: 'If evidence is absent, end the trace at ABSTAIN. Do not synthesize a value or a source.',
    mobile: 'Render the trace as a numbered vertical record; never hide source fingerprints in a drawer.',
    panels: [
      { label: 'Step 01 · intake', title: 'Load governed fields', body: 'Closing NAV · Committed capital · Complaints closed', meta: 'FIXED SYNTHETIC CASE' },
      { label: 'Step 02 · compare', title: 'Normalize candidate values', body: 'Equality only; source count does not resolve disagreement.', meta: 'DETERMINISTIC PATH' },
      { label: 'Step 03 · propose', title: 'Surface support or conflict', body: 'Proposal only; no filing or compliance conclusion.', meta: 'HUMAN REVIEW BOUNDARY' },
      { label: 'Step 04 · abstain', title: 'Investor complaints closed', body: 'No candidate evidence is present.', meta: 'OUTPUT / UNSUPPORTED' },
    ],
  },
  {
    number: '05',
    slug: 'risk-board',
    name: 'Risk and anomaly board',
    task: 'Show deterministic risk indicators and anomaly flags computed from the same evidence record, each closed by a named human disposition.',
    action: 'Disposition remaining flags',
    error: 'A flag stays open, visible, and un-resolved until a named human escalates or acknowledges it with a reason.',
    mobile: 'Stack indicator cards one per row; keep each flag card whole with its disposition form directly beneath it.',
    panels: [
      { label: 'Risk indicator', title: 'Evidence coverage', body: '2/3 fields carry candidate evidence', meta: 'COMPLIANCE LENS' },
      { label: 'Anomaly flag · HIGH', title: 'Duplicate document fingerprint', body: 'Two distinct claimed sources share one fingerprint.', meta: 'FRAUD ANALYSIS LENS' },
      { label: 'Anomaly flag · MEDIUM', title: 'Conflict resolved toward higher value', body: 'Fires only once the higher candidate is accepted.', meta: 'FRAUD ANALYSIS LENS' },
      { label: 'Disposition', title: 'Escalate or acknowledge', body: 'Disposer name and reason required before sign-off.', meta: 'NAMED HUMAN REQUIRED' },
    ],
  },
  {
    number: '06',
    slug: 'review-signoff',
    name: 'Review and sign-off',
    task: 'Review accepted, corrected, rejected, and deferred decisions before producing a local evidence receipt.',
    action: 'Resolve conflict before sign-off',
    error: 'Sign-off remains blocked while the capital conflict lacks a named reviewer and reason, or any anomaly flag lacks a disposition.',
    mobile: 'Place blocked state before the decision table; move each row into a labeled definition list.',
    panels: [
      { label: 'Decision ledger', title: 'Closing NAV', body: 'Awaiting human action', meta: 'SUPPORTED EVIDENCE · NOT SIGNED OFF' },
      { label: 'Decision ledger', title: 'Committed capital', body: 'Reviewer and reason missing', meta: 'BLOCKING CONFLICT' },
      { label: 'Decision ledger', title: 'Investor complaints closed', body: 'Evidence request remains open', meta: 'UNRESOLVED · NON-BLOCKING EXPORT' },
      { label: 'Principal Officer confirmation', title: 'Second named role required', body: 'Officer (demo) name and confirmation checkbox. Blocked until the conflict is decided and every flag is dispositioned.', meta: 'MAKER-CHECKER SEPARATION REQUIRED' },
    ],
  },
  {
    number: '07',
    slug: 'evidence-receipt',
    name: 'Evidence receipt',
    task: 'Package source fingerprints, candidate coordinates, human decisions, risk indicators, and unresolved items into a printable local record.',
    action: 'Export local evidence receipt',
    error: 'If unresolved items remain, export them prominently; never describe the receipt as approval or verification.',
    mobile: 'Use a single-column manifest; preserve fingerprints as wrapping mono text without horizontal scrolling.',
    panels: [
      { label: 'Receipt scope', title: 'meridian-horizon-q2-2026', body: 'Research-stage synthetic case', meta: 'NOT A REGULATORY FILING' },
      { label: 'Input fingerprint', title: 'Administrator statement', body: 'Page 2 · capital summary', meta: 'synthetic:admin-statement:9b2d7f' },
      { label: 'Input fingerprint', title: 'Internal ledger extract', body: 'NAV ledger · cell F18', meta: 'synthetic:ledger:38a4c1' },
      { label: 'Risk summary', title: '4 anomaly flags · 0 open', body: 'Committed capital · Investor complaints closed', meta: 'HUMAN DECISION REQUIRED' },
    ],
  },
];
